CompanyProject.API/Controllers/MenuFirstLineController.cs
using HelpClasses;
using Microsoft.AspNetCore.Mvc;
using RefitInterfaces;

namespace CompanyProject.API.Controllers;

public class MenuFirstLineController : Controller
{
    private readonly IContentServiceContent _contentServiceContent;
    private readonly IContentServicePriceList _contentServicePriceList;

    public MenuFirstLineController(IContentServicePriceList contentServiceProList,
        IContentServiceContent contentServiceContent)
    {
        //_unitOfWork = unitOfWork;
        _contentServicePriceList = contentServiceProList;
        _contentServiceContent = contentServiceContent;
    }

    [Route("/comments")]
    public IActionResult Comments()
    {
        return View();
    }

    /// <summary>
    ///     Возвращает fullpricelist из микросервиса CompanyProjectPriceListService
    /// </summary>
    /// <returns>Спикок PriceListDto</returns>
    [Route("/fullpricelist")]
    public async Task<IActionResult> FullPriceList()
    {
        var result = (await _contentServicePriceList.GetPriceList("full")).OrderBy(p => p.PriceListId)
            .Distinct(new PriceListDtoComparer()).ToList();
        return View(result);
    }

    [Route("/about")]
    public async Task<IActionResult> About()
    {
        var companyInfo = await _contentServiceContent.GetCompanyContactAsync(true);
        return View("About", companyInfo);
    }

    [Route("/contacts")]
    public async Task<IActionResult> Contacts()
    {
        var companyInfo = await _contentServiceContent.GetCompanyContactAsync(true);
        return View("Contacts", companyInfo);
    }
}

CompanyProject.API/Controllers/ServiceController.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using System.Text.Unicode;
using AutoMapper;
using Dto;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Operations;
using RefitInterfaces;

namespace CompanyProject.API.Controllers;

public class ServiceController : Controller
{
    private readonly IContentServiceMessage _contentServiceMessage;

    //private readonly ILogger _logger;

    //private readonly IMapper _mapper;


    public ServiceController(/*IMapper mapper,*/
       /* IContentServiceMessage contentServiceMessage*/)
    {
        //_logger = Log.CreateLogger<HomeController>();
        //_mapper = mapper;
        //_contentServiceMessage = contentServiceMessage;
    }

    //public async Task<IActionResult> AddMessageToDbAsyncTask(MessageDto mes)
    //{
    //    if (!ModelState.IsValid) 
    //        return Json(JsonSerializer.Serialize(new {parameter = "error"}));
    //    if (!mes.IsAdoptedPrivacyPolicy)
    //    {
            
    //        return Json(JsonSerializer.Serialize(new {parameter = "warning"}));
    //    }

    //    var sha512 = SHA512.Create();
    //    var resultShaHash = sha512.ComputeHash(Encoding.Unicode.GetBytes(JsonSerializer.Serialize(mes)));
    //    var shaToText = Encoding.Unicode.GetString(resultShaHash);
    //    var dic = new Dictionary<string, string> {{shaToText, JsonSerializer.Serialize(mes)}};
    //    var response = await _contentServiceMessage.Post(dic);
    //    if (!response.IsSuccessStatusCode)
    //        return Json(JsonSerializer.Serialize(new {parameter = "error"}));
    //    return Json(JsonSerializer.Serialize(new {parameter = "ok"}));
    //}

    //[HttpPost]
    //public async Task<IActionResult> MakeOrderConfirmResult()
    //{
    //    try
    //    {
    //        if (TempData.ContainsKey("orderViewModel"))
    //        {
    //            var isNewCustomer = true;
    //            var orderViewModel =
    //                JsonSerializer.Deserialize<OrderViewModel>((TempData["orderViewModel"] as string));
    //            var customer = (await _unitOfWork.Customers.GetWithInclude(p => p.Orders))
    //                .FirstOrDefault(p => p.PhoneNumber == orderViewModel.PhoneNumber);
    //            if (customer == null)
    //            {
    //                customer = _mapper.Map<Customer>(orderViewModel);
    //                await _unitOfWork.Customers.AddEntityAsync(customer);
    //            }
    //            else
    //                isNewCustomer = false;
    //            var order = _mapper.Map<Order>(orderViewModel);
    //            order.CreateTime = DateTime.Now.ToString(CultureInfo.CurrentCulture);
    //            if (!isNewCustomer)
    //                _unitOfWork.Customers.UpdateEntity(customer);
    //            var onePrice = await _unitOfWork.PriceLists.GetAllEntity()
    //                .FirstOrDefaultAsync(p => p.Service == order.TypeOfFailure
    //                    .Substring(order.TypeOfFailure.IndexOf("- "))
    //                    .Remove(0, 2));
    //            string minPrice = (onePrice == null)
    //                ? "Стоимость будет определена после диагностики"
    //                : onePrice.ServicePrice;
    //            order.Price = decimal.TryParse(minPrice, out var price)
    //                ? price
    //                : 0;
    //            var lastOrderNumber = await _unitOfWork.Orders.GetAllEntity().MaxAsync(p=>p.OrderNumber);
    //            order.OrderNumber = ++lastOrderNumber ?? 1;
    //            customer.Orders.Add(order);
    //            await _unitOfWork.CompleteAsync();
    //            var makeOrderResultDic = new Dictionary<string, string>()
    //            {
    //                {"Ваш номер заказа:", order.OrderNumber.ToString()},
    //                {"Причина вызова мастера:", order.TypeOfFailure},
    //                {"Время прихода мастера:", order.VisitTime},
    //                {"Минимальная (ориентировочная) стоимость:", minPrice}
    //            };
    //            return PartialView("ContentViews/PartialView/_MakeOrderResult", makeOrderResultDic);

    //        }
    //        else
    //            return StatusCode(405);
    //    }
    //    catch (Exception)
    //    {
    //        _unitOfWork.Dispose();
    //        return StatusCode(405);
    //    }
    //}

    public IActionResult MakeOrder()
    {
        var orderViewModelDto = new OrderViewModelDto();
        return View(orderViewModelDto);
    }

 public IActionResult MakeOrderConfirm(OrderViewModelDto order)
    {
        if (ModelState.IsValid)
        {
            if (order != null)
            {
                var orderProperties = order.GetType().GetProperties();
                var dictionaryAttributes = new Dictionary<string, string>();
                foreach (var propertyInfo in orderProperties)
                {
                    if (propertyInfo.GetValue(order) == null) propertyInfo.SetValue(order, "Отсутствует");

                    if (propertyInfo.GetCustomAttribute<DisplayAttribute>() != null)
                        dictionaryAttributes.Add(propertyInfo.GetCustomAttribute<DisplayAttribute>().Name,
                            propertyInfo.GetValue(order).ToString());
                }

                var options = new JsonSerializerOptions
                {
                    Encoder = JavaScriptEncoder.Create(UnicodeRanges.All),
                    WriteIndented = true
                };
                return PartialView("ContentViews/PartialView/_MakeOrderConfirm", dictionaryAttributes);
            }

            return NotFound();
        }

        return View("Error");
    }
}

CompanyProject.API/Views/Shared/Components/TopMenu/TopMenu.cshtml
@model Dictionary<string, List<Dto.TopMenuEntityDto>>

<div class="container is-hidden-mobile">
    <div class="columns">
        @foreach (var t in Model["firstLine"])
        {
            @if (t.NeedStar)
            {
                <div class="column has-text-centered is-hidden-mobile">
                    @for (var i = 0; i < 5; i++)
                    {
                        <i class="@t.Icon" style="color: @t.IconColor"></i>
                    }
                    <a asp-controller="@t.AspController" asp-action="@t.AspAction">
                        <span class="has-text-black">&nbsp;<u>@t.ScreenName</u></span>
                    </a>
                </div>
                continue;
            }
            <div class="column has-text-centered">
                <a asp-controller="@t.AspController" asp-action="@t.AspAction">
                    <i class="@t.Icon" style="color: @t.IconColor"></i>
                    <span class="has-text-black">&nbsp;&nbsp;&nbsp;<u>@t.ScreenName</u></span>
                </a>
            </div>
        }
    </div>
</div>
<hr class="is-hidden-mobile" style="margin-top: 10px;"/>

<div class="container" style="background: white">
    <partial name="ContentViews/PartialView/_TopMenuForMobile"/>
    <div class="columns is-hidden-touch">
        <div class="column font-title">
            <a asp-controller="Home" asp-action="Index">
                @(new HtmlString(companyInfo.Company_Info.CompanyName))
            </a>
        </div>
        <div class="column">
            <a asp-fragment="short-message">
                <i class="fas fa-phone-square-alt" style="color: black; font-size: 18px;"></i>
                <span class="has-text-black">&nbsp;&nbsp;&nbsp;<span class="term">Заказать обратный звонок</span></span>
            </a>
            <br/>
            <a asp-fragment="short-message">
                <i class="fas fa-mail-bulk" style="color: black; font-size: 18px;"></i>
                <span class="has-text-black">&nbsp;&nbsp;<span class="term">Отправить сообщение с вопросом</span></span>
            </a>
        </div>
        <div class="column" style="margin-left: 0.75rem;">
            <i class="fas fa-phone-volume" style="color: black; font-size: 24px;"></i>
            <span class="font-tel">&nbsp;@(new HtmlString(companyInfo.Company_Info.CompanyPhoneNumber))</span> <br/>

            <i class="fas fa-comment-alt" style="color: black; font-size: 18px;"></i>
            <span>&nbsp;&nbsp;&nbsp;WhatsApp: @(new HtmlString(companyInfo.Company_Info.CompanyMessagerNumber))</span>

        </div>
        <div class="column" style="margin-left: 0.75rem; margin-top: -20px;">
            <span class="font-title">Нужна помощь?</span>
            <br/>
            <a asp-controller="Service" asp-action="MakeOrder" class="button is-primary" style="padding-right: 40px;">
                <i class="fas fa-wrench" style="font-size: 18px">&nbsp;</i>
                <b>&nbsp;&nbsp;&nbsp;ВЫЗВАТЬ МАСТЕРА</b>
            </a>
        </div>
        @*<div class="column">
            <a href="#" class="button is-warning">
            <strong>Зарегистрироваться</strong>
            </a> <br />
            <a href="#" class="button is-success">
            <strong>Вход</strong>
            </a>
            </div>*@
    </div>
</div>
<br/>

<nav class="navbar is-link " role="navigation">
    <div class="container">
        <div class="navbar-brand  is-hidden-desktop">
            <a class="navbar-item font-title" style="font-size: 20px" asp-controller="MenuFirstLine" asp-action="FullPriceList">
                Цены на услуги
            </a>
            <a class="navbar-item font-title" style="font-size: 20px" asp-controller="MenuFirstLine" asp-action="Contacts">
                Контакты
            </a>
            <a role="button" class="navbar-burger burger" data-target="navbarMenu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>
        <div id="navbarMenu" class="navbar-menu ">
            <div id="basicNavBarMenu" class="navbar-start">
                @foreach (var m in Model["topMenuNavBar"].Where(m => m.NavBar))
                {
                    <a class="navbar-item font-title" style="font-size: 1.1em" asp-controller="@m.AspController" asp-action="@m.AspAction">
                        <i class="@m.Icon">&nbsp;</i>
                        <span>@m.ScreenName</span>
                    </a>
                }
            </div>
            <div id="fullNavBarMenu" class="navbar-start is-hidden">
                @foreach (var m in Model["topMenuNavBar"])
                {
                    <a class="navbar-item " asp-controller="@m.AspController" asp-action="@m.AspAction">
                        <i class="@m.Icon">&nbsp;</i>
                        <span>@m.ScreenName</span>
                    </a>
                }

            </div>

        </div>
    </div>
</nav>